### ISSUE TITLE
Guest login doesn't work. Pressing Enter key after entering a code, or clicking Enter button on page both do nothing

### ISSUE THREAD

**Issue by jacksonmeyn** [Aythir/JCJS.ComputingProject2018_S2#1]

**Comment by Aythir** [comment]
Hi Jackson

Solved the issue in a new branch and merged it to master.

Thank you!

**Comment by jacksonmeyn** [comment]
The changes you made in index.html needed to be added to index.php. Have done now. Also edited gallery.php to accept POST submission from index.php
