### ISSUE TITLE
gallery.php - Guests should be able to add more unique unique codes once logged in - modal?

### ISSUE THREAD

**Issue by jacksonmeyn** [Aythir/JCJS.ComputingProject2018_S2#103]
Currently guests can add one unique code at login. It would be good if they could add more - maybe via a modal - from the gallery page.

I think there's already an UniqueCodes array in the SESSION variables on the gallery.php page so the modal would need be able to add to this.

Ask if any clarification needed :)

**Comment by posmarket** [comment]
I think this is complete now.
