### ISSUE TITLE
Slideshow.php - not scrolling through photos

### ISSUE THREAD

**Issue by clea1** [Aythir/JCJS.ComputingProject2018_S2#145]

**Comment by posmarket** [comment]
Not sure about this one. It seems to relate to the version of bootstrap.css that we're using. If I replace the link to the current CSS file with the link below it works.
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
But that breaks the navbar.
@clea1 which version of CSS is the local file?
