### ISSUE TITLE
hostLogin - colour issues

### ISSUE THREAD

**Issue by clea1** [Aythir/JCJS.ComputingProject2018_S2#17]
Needs a white background on form

**Comment by posmarket** [comment]
Is this how it should look clea?
![image](https://user-images.githubusercontent.com/2866571/43041640-c814a98a-8da9-11e8-9db8-dc9fa1cf6696.png)

**Comment by clea1** [comment]
Don't know what I was on when I created this one. Sorry, see other Host login issue.
