### ISSUE TITLE
hostLogin.php - layout not as HTML

### ISSUE THREAD

**Issue by clea1** [Aythir/JCJS.ComputingProject2018_S2#18]
This PHP page does not look like the original HTML file, as shown below (from original HTML file)
![image](https://user-images.githubusercontent.com/39670057/42985647-babd4ac8-8c35-11e8-9b5a-f212ad3c944d.png)

**Comment by posmarket** [comment]
Fixed

**Comment by clea1** [comment]
The HTML file host_login.html is fine. But currently the PHP page looks like;
![image](https://user-images.githubusercontent.com/39670057/43042553-99adebfe-8dc4-11e8-9f4d-745cc8f1f453.png)
It should look like:

![image](https://user-images.githubusercontent.com/39670057/43042561-b924f220-8dc4-11e8-91fc-24c66383efdf.png)

**Comment by clea1** [comment]
Layout is now correct, just need:

- to remove social media icons

- and add the 'Terms of Use and Privacy Policy' link text

**Comment by clea1** [comment]
Decide to closed this issue and create a new one for new issues
