### ISSUE TITLE
create_new_event - add modal to Logout button

### ISSUE THREAD

**Issue by clea1** [Aythir/JCJS.ComputingProject2018_S2#31]
Add success modal to 'Log out' button

**Comment by clea1** [comment]
I don't know how to add the modal to 'Logout' nav item when it is part of navbarlink (see image below). Please help.
![logout](https://user-images.githubusercontent.com/39670057/43997720-ef7488aa-9e26-11e8-9cff-e9eb5519438d.JPG)

**Comment by posmarket** [comment]
See answer on other issue.
