### ISSUE TITLE
gallery.php : add modal to logout button

### ISSUE THREAD

**Issue by clea1** [Aythir/JCJS.ComputingProject2018_S2#34]
Add Logout button - Done

**Comment by clea1** [comment]
Logout nav text added, just need modal when pressed

**Comment by clea1** [comment]
I don't know how to add the modal to 'Logout' nav item when it is part of navbarlink (see image below). Please help.
![logout](https://user-images.githubusercontent.com/39670057/43997637-5beaa346-9e24-11e8-9607-b3bab3cd2bd3.JPG)

**Comment by posmarket** [comment]
I've created a 'logout.php' file to destroy the session and redirect user to the login page. I've created a new function in the functionList.php page to allow the logout modal to work. See gallery.php for an example.
