### ISSUE TITLE
index.php: compare code to host_login.php to correct a few issues

### ISSUE THREAD

**Issue by clea1** [Aythir/JCJS.ComputingProject2018_S2#35]
Use Host_login.php code to correct the following issues:
-'Enter' button should not take user to gallery without correct input, add error message if Enter clicked without input.
-Add success modal on correct input
-Correct 'code' positioning

**Comment by clea1** [comment]
fixed - correct 'code positioning
fixed - ENTER button now does not link to gallery now
needs work - Modal added, but need Event code functionality - (correct php and id to be used)
@posmarket need help with this, what is eventCode correct id? please have a look.

**Comment by posmarket** [comment]
Fixed this issue. Entering event valid code allows user to proceed to gallery.
