### ISSUE TITLE
Navigation on most pages need checking

### ISSUE THREAD

**Issue by clea1** [Aythir/JCJS.ComputingProject2018_S2#7]
Check that navigation menu on each page are present and correct. 
For instance, do we want the Create Gif and Apply Filters to show on the Slideshow.php page?

**Comment by posmarket** [comment]
I think the navigation is sorted now.

**Comment by clea1** [comment]
This issue was referring to the PHP pages and a lot are still missing any menu items. 
admin_create_event.php
admin_change_password.php
admin_create_event.php
slidesho.php nav items link to html pages

**Comment by posmarket** [comment]
I think these issues are sorted now. The first three pages have 
Slideshow.php nav items link to php pages.
Logout functionality with modal added to all pages (I think).
