### ISSUE TITLE
gallery.php - create animation only allows selection from booth images

### ISSUE THREAD

**Issue by jacksonmeyn** [Aythir/JCJS.ComputingProject2018_S2#75]
Create gif only allows selection of booth images, which is correct, but the public uploads div is still visible while the user is selecting images for the gif, which means they'll think they can add images from that section to the gif. We should hide that div while the selection mode is active

**Comment by posmarket** [comment]
Done. Public gallery hidden while animation options are open. Public gallery returns when animation is cancelled.
