### ISSUE TITLE
index.php layout - scrolling should not be required on this page

### ISSUE THREAD

**Issue by jacksonmeyn** [Aythir/JCJS.ComputingProject2018_S2#76]
Tested in multiple browsers on iOS. Let's rethink layout so all content fits on one mobile screen

**Comment by posmarket** [comment]
I've made some changes to the wording and removed the second header. Let me know your thoughts.

**Comment by jacksonmeyn** [comment]
Yes just tested in Safari, Chrome and Firefox on iOS. Looks much better, thanks Steve :)
