### ISSUE TITLE
uploadPhoto.php - "take a photo now" button not working on iOS

### ISSUE THREAD

**Issue by jacksonmeyn** [Aythir/JCJS.ComputingProject2018_S2#83]
Tested in Firefox and Safari on iOS11. Tapping "take a photo now" will bring up the camera and allow a photo to be taken, but will do nothing afterwards.

Tapping "select photos" button however, brings up an iOS dialogue that asks the user to select a photo from library or take one now, and proceeds correctly no matter which is selected.

Haven't tested on Android, so depending on how that goes maybe we can do away with "take a photo now" button altogether

**Comment by posmarket** [comment]
I think you're right Jackson. I've got an older Android phone here and it brings up a similar dialog to the one on iOS.
