### ISSUE TITLE
uploadPhoto.php - Crop to correct resolution

### ISSUE THREAD

**Issue by jacksonmeyn** [Aythir/JCJS.ComputingProject2018_S2#86]
This may have already been done but just checking. 

Uploaded landscape photos should be cropped to 1620 x 1080 or closest possible 3:2 aspect ratio. Portrait orientation should be cropped to 720 x 1080 or closest possible 2:3 aspect ratio.

After upload, Jackson's createThumbnail.php script should handle thumbnail creation

**Comment by posmarket** [comment]
Done. Needs testing though.
