### ISSUE TITLE
gallery.php - download all photos doesn't seem to work

### ISSUE THREAD

**Issue by jacksonmeyn** [Aythir/JCJS.ComputingProject2018_S2#88]
On desktop and iOS at least, redirects to ajaxDownloadAllPhotos.php and displays digit 0

**Comment by posmarket** [comment]
Seems like a permissions issue. Jackson can you check?

**Comment by jacksonmeyn** [comment]
OK will do

**Comment by jacksonmeyn** [comment]
Permissions issue fixed. Thanks @posmarket :)
