### ISSUE TITLE
admin_event_details.php layout issue

### ISSUE THREAD

**Issue by jacksonmeyn** [Aythir/JCJS.ComputingProject2018_S2#89]
Problem as below on desktop Firefox and Chrome at 1366 x 768
![image](https://user-images.githubusercontent.com/30762914/44640834-5279b100-aa07-11e8-8789-77233fd2e67b.png)

**Comment by clea1** [comment]
This seems to be fixed at that size. Only issue is on small devices, there is a similar thing as above happening.

**Comment by clea1** [comment]
Yep
